<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<head>
    <title>memberCreate</title>
<style>
th{
text-align:center;
}
body{
font: 16px Arial, sans-serif;
}
</style>
</head>

<body>
<form:form method="post" action="processAgent.html" modelAttribute="memberCreateForm">
<h2 style="background-color:${currUser.role.color}">${currUser.role.desc}&nbsp; ${currUser.contact} - Create ${currRole.desc}:</h2>
<table border="0" cellpadding="3" cellspacing="0" width="500">
<tbody align="left" style="font-family:verdana; color:purple; background-color:${currRole.color}">
<tr>
<td width="30%">Email (Logon Username)*:</td>
<td width="70%"><input type="text" style='width:20em' name="newProfile.email" value="${memberCreateForm.profile.email}"/></td>
</tr>
<tr>
<td width="30%">Password (Autogenerated):</td>
<td width="70%"><input type="text" name="newPassword"
	maxlength="0" value="${memberCreateForm.password}" readonly /></td>
</tr>
<tr>
<td width="30%">Contact*:</td>
<td width="70%"><input type="text" name="newProfile.contact" value="${memberCreateForm.profile.contact}" /></td>
</tr>
<tr>
<td width="30%">Phone*:</td>
<td width="70%"><input type="text" name="newProfile.phone" value="${memberCreateForm.profile.phone}"/></td>
</tr>
</tbody>
</table>
<br/>
<tr><td>*required field</td></tr>
<br/>
<tr><td><font color="red" size="3">${memberCreateForm.message}</font></td></tr>
<br/>
<table border="0" cellpadding="3" cellspacing="0" width="600">
<tbody align="left" style="font-family:verdana; color:purple; background-color:White">
<tr>
<td><input type="submit" name="member_create" value="Save" class="button" style="height:23px;"/></td>
<td><input type="submit" name="member_cancel" value="Cancel" class="button" style="height:23px;"/></td>
</tr>
</tbody>
</table>
</form:form>

</body>
</html>
